Features/search result skeleton 103
iandusenbury/tableland pull request #16
Opened 2018-02-01 03:04 UTC by mballeza

2018-02-01 04:47 UTC, iandusenbury requested changes

2018-02-01 04:47 UTC, iandusenbury commented on client/src/containers/searchresults/displaytable.js
> +            const isStripedButton = (index) => {
I'm pretty sure we can just do this in css. There is a :even/:odd pseudo selector
https://stackoverflow.com/questions/5080699/using-css-even-and-odd-pseudo-classes-with-list-items

2018-02-01 04:47 UTC, iandusenbury commented on client/src/containers/searchresults/displaytable.js
> +                    <li>LinkedIn: { user.linkedin_id }</li>
I know this is all dummy data but if we want to be able to plug our stuff in then all our variables should be camel case so org_name -> orgName, if you want it to be really ready for actual data then use the exact names in the design doc (again, not sure if necessary right now)

2018-02-01 04:47 UTC, iandusenbury commented on client/src/containers/searchresults/index.js
> +          <FlatButton href='#top' flat>{'Return to top of results'}</FlatButton>
I'm getting an error in the console here, it wants flat='true'

2018-02-01 04:47 UTC, iandusenbury commented on client/public/index.html
> +    <!--link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css"-->
Are we using this? if not remove line

2018-02-01 04:47 UTC, iandusenbury commented on client/package.json
> +    "react-toolbox": "^2.0.0-beta.12",
remove line and run 'yarn' to regenerate yarn.lock

2018-02-01 04:47 UTC, iandusenbury commented on client/package.json
> +    "react-bootstrap": "^0.32.0",
Are we using react-bootstrap? if not remove line and run 'yarn' to regenerate yarn.lock

2018-02-01 04:47 UTC, iandusenbury commented on client/src/containers/searchresults/displaytable.js
> +import React from 'react'
I put this at the top so you'd see it first. The more we can abstract logic from the return function the better. You have all the pieces there and the map function is exactly what we want to do but here are my suggestions for this file as you have it now:
```
import React, { Component } from 'react'
import { bindActionCreators } from 'redux'
import { connect } from 'react-redux'
import {
  Table,
  TableBody,
  TableRow,
  TableRowColumn,
  Avatar,
  FlatButton,
} from 'material-ui'

class DisplayTable extends Component {
  constructor(props) {
    super(props)

    this.renderTableRows = this.renderTableRows.bind(this)
  }

  renderTableRows() {
    const { users } = this.props

    const tableRows = users.map((user) => {
      const {
        id,
        first_name,
        last_name,
        org_name,
        linkedin_id,
        contact_url
      } = user

      const isStriped = (index) => {
        if (index % 2) return '#8195b1'
        return 'white'
      }
      const isStripedButton = (index) => {
        if (!(index % 2))
        return '#f8f8f8'
      }

      return (
        <TableRow style={{backgroundColor: isStriped(id)}} key={id}>
          <TableRowColumn className='table-cell'>
            <div className='table-name' style={{borderBottomColor: isStriped(id+1)}}>
              <h2>{first_name} {last_name}</h2>
            </div>
            <div className='table-icon' style={{borderRightColor: isStriped(id+1)}}>
              <div style={{paddingLeft: '12px'}}>
                <Avatar size={60} src={require('./portrait.png')} />
              </div>
              <FlatButton hoverColor={isStripedButton(id+1)} style={{float: 'left'}}>View profile</FlatButton>
            </div>
            <div className='table-about'>
              <ul>
                <li>Works at: {org_name}</li>
              </ul>
            </div>
            <ul className='table-contact'>
              <li>LinkedIn: {linkedin_id}</li>
              <li>Contact: {contact_url}</li>
            </ul>
          </TableRowColumn>
        </TableRow>
      )
    })

    return tableRows
  }

  render() {
    return (
      <Table selectable={false}>
        <TableBody displayRowCheckbox={false} stripedRows>
          {this.renderTableRows()}
        </TableBody>
      </Table>
    )
  }
}

export default connect(
)(DisplayTable)

```

2018-02-01 04:47 UTC, iandusenbury commented on client/src/containers/searchresults/style.css
> +  }
space after

2018-02-01 04:47 UTC, iandusenbury commented on client/src/containers/searchresults/displaytable.js
> +                    <div style={{paddingLeft: '12px'}}>
no inline styles, give it a class name and style with css

2018-02-01 19:00 UTC, mballeza commented
Ready for another review.

2018-02-02 23:44 UTC, iandusenbury approved these changes

2018-02-03 00:09 UTC, Domicilius approved these changes

2018-02-03 00:56 UTC, merged