Features/edit profile setup 61
iandusenbury/tableland pull request #30
Opened 2018-02-19 05:09 UTC by halalak

2018-02-19 22:31 UTC, Domicilius requested changes
Some of the styling is messing up the /organization page. Are any of the styling files affecting all material UI components or similar?

On the edit profile page itself: Where is the save/submit button going to go?

2018-02-20 01:10 UTC, mballeza requested changes
The view will look good once we fix our styling problem. A few things I've noticed:
-Add styles to widgets: few places with MUI components that still use inline stying.
-Linting: code spacing.
-Suggestion: with nth-child(n) instead of "odd" or "even" you can use an index so you don't unintentionally apply the styling to other elements.
-AppBar components: mouse hover makes it look clickable.

These below will probably be fixed when we fix all of our styling.
-Native css elements: these (and all of our other styles) will need to be segregated into classes so they don't override other pages.
-Avatar not centered: slightly higher than center.
-Button highlight: highlight doesn't cover the entire button.
-Scroll bar: the horizontal and vertical scrollbar is present in full screen.

I am curious about the date picker component. Do we have to be specific to a day of start/end date? Could the date picker pick a month rather than a day?

2018-02-21 18:29 UTC, djarredon requested changes
The page has a horizontal scrollbar at the bottom, which shouldn't be necessary. I might have a smaller screen than others in the group, but I tried looking at the screen with the Chrome dev tools as well, and it looks like it stayed there at any screen size. Also, there are two vertical scrollbars. I will try applying the styling I used to get the profile pages working and will suggest it if it works.
Also, the Edit button under the user Avatar isn't inside the Paper component like it's supposed to be. This and the horizontal scrollbar should be fixed.

2018-02-23 21:19 UTC, djarredon approved these changes

2018-02-24 00:54 UTC, mballeza approved these changes

2018-02-24 01:14 UTC, merged