Features/populate professional fields 57
iandusenbury/tableland pull request #47
Opened 2018-03-01 21:22 UTC by djarredon

Please give me comments on how we want the video to display.
You may need to run _rails db:reset_ and _rails db:seed_ for the profile view to show samples properly.

2018-03-01 22:12 UTC, mballeza commented on client/src/components/professional/style.css
> +  height: 30vh;
I think the height and width should be the same value, like 40vh and 40vw. It looks better but doesn't push down the experiences list too much.

2018-03-01 22:13 UTC, mballeza commented on client/src/components/edit/edit.css
> +<<<<<<< HEAD
Remove git conflict inserts.

2018-03-01 22:16 UTC, mballeza commented on client/src/components/professional/index.js
> +        <p>{startDate} - {endDate}</p>
We should parse these dates and convert them to readable dates like "Jan 2005 - May 2014" or "Jan 2005 - Present".

2018-03-01 22:20 UTC, mballeza commented on client/src/components/professional/style.css
> +  frameborder: 0;
Move this frameborder as a prop to the iframe tag to get rid of the border around the video.

2018-03-01 22:25 UTC, mballeza requested changes
See my comments in the review. A couple of additional things:
-Needs lint fixes
-Remove unused css classes from styles.css
-The video player could use a margin below to put more separation between the divider
-The text below the avatar profile pic should be centered. Should we be having the background container change size with the amount of text? What if the text overflows?

2018-03-02 20:43 UTC, mballeza requested changes
Looks like yarn lintfix isn't working the way we want it to. Run "yarn eslint" on the relevant folders, but I don't think we have an eslint-fix to auto-fix everything.
The video player looks great now, just needs a margin between the divider.

2018-03-02 20:46 UTC, iandusenbury commented
`yarn lintfix` will fix any formatting errors. `yarn lint` will show linting errors across the whole project

2018-03-04 03:49 UTC, iandusenbury approved these changes

2018-03-04 03:49 UTC, iandusenbury commented on client/src/actions/index.js
> +export function fetchProfessional(userID) {
As a default we could pass in 'random' as our id, so
`export function fetchProfessional(userId = 'random')`
This would make the function use random if no userID is provided
Then our endpoint would be what you have commented out

2018-03-04 03:49 UTC, iandusenbury commented on client/src/components/professional/index.js
> +    this.props.fetchProfessional(3)
Still have an id passing through here

2018-03-04 03:49 UTC, merged