Features/populate organization fields 114
iandusenbury/tableland pull request #48
Opened 2018-03-01 22:01 UTC by djarredon

2018-03-01 22:32 UTC, mballeza commented on client/src/components/organization/index.js
> +    if (media && media[0])
Use the same "reducedMedia" function used in the organization reducer to get the url of the image. I'm not sure if it's safe to assume that the image is always in index 0.

2018-03-01 22:37 UTC, mballeza requested changes
Just the one review comment in addition to the reviews I made for the professional branch. The employee table looks good. If you want to see an org with at least one employee, try an ID of 34 or 36.

2018-03-02 20:46 UTC, mballeza requested changes
Looks great, see the review from the professional branch, then I'll approve.

2018-03-02 21:12 UTC, iandusenbury approved these changes

2018-03-05 21:49 UTC, mballeza requested changes
Has some linting errors still in components/organization and the reducer. I'm getting some errors in the console related to the video player, though I'm not sure if it has to be addressed right now. Other than that, the page itself looks great! Just needs a merge with the current dev branch and it'll be good to go.

2018-03-07 01:26 UTC, mballeza approved these changes

2018-03-07 03:38 UTC, merged