Features/professional cleanup 156
iandusenbury/tableland pull request #85
Opened 2018-03-24 22:25 UTC by djarredon

Orders experiences by end date on professionals' page.

2018-03-30 19:16 UTC, djarredon commented
If anyone has time to test this then that'd be awesome. I'll be doing some more testing of my own, but another pair of eyes would be great.

2018-04-05 18:12 UTC, mballeza requested changes
The list seems to be sorted with most current end date first, with all null end dates (current experiences) at the end. I think you meant to have least recent end date first? Also, what is your rationale for sorting by end date?

2018-04-05 18:12 UTC, mballeza commented on client/src/components/professional/index.js
> +    return new Date(b.endDate) - new Date(a.endDate)
Should this be
```javascript
return new Date(a.endDate) - new Date(b.endDate)
```

2018-04-05 18:13 UTC, mballeza commented on client/src/components/professional/index.js
> +    return new Date(b.endDate) - new Date(a.endDate)
See my other comment

2018-04-05 18:23 UTC, mballeza commented on client/src/components/professional/index.js
> +    if (!b.endDate)
After clarifying how the list is supposed to be sorted, I believe this if section (if no b.endDate) should return positive, since we want anything with no end date to be listed first.

2018-04-05 18:36 UTC, mballeza commented on client/src/components/professional/index.js
> +    return new Date(b.endDate) - new Date(a.endDate)
Add same logic from orgList sorting to have nested programs sorting correctly:
```javascript
  if (!a.endDate)
    return -1
  if (!b.endDate)
    return 1
```

2018-04-05 18:50 UTC, mballeza approved these changes

2018-04-05 19:35 UTC, merged